### ISSUE TITLE
라디오버튼 값 조건에 따른 텍스트박스 활성화/비활성화가 잘 안되요

### ISSUE THREAD

**Issue by nhki01** [2021-SMHRD-KDT-IoT-1/RENTUE#39]
라디오버튼 값 조건에 따른 텍스트박스 활성화/비활성화가 잘 안되요
라디오버튼 관제소를 클릭 시 텍스트박스 중 rent_name, rent_num을 비활성화 시키고 싶습니다

**Comment by kyg4914** [comment]
앞에 질문 해결하고 갈게요!

**Comment by kyg4914** [comment]
jquery 라이브러리 경로 설정, 코드 순서 조정
