### ISSUE TITLE
ajax key:value 형태로 값 넘기기 및 동적 select encoding 도와주세요

### ISSUE THREAD

**Issue by nhki01** [2021-SMHRD-KDT-IoT-1/RENTUE#41]
ajax 현재 string 3개만 넘기고 있는데 key:value 형태로 3개의 값 넘기기 하고 싶습니다.
그리고 동적 select 값 ajax로 넘겨올때 encoding이 안됩니다.

**Comment by kyg4914** [comment]
보낼 값들을 JSONObject로 리턴
한글인코딩 : response.setContentType으로 인코딩 방식을 지정후에 PrintWriter 객체 생성
